// Code generated by ogen, DO NOT EDIT.

package dadata

import (
	ht "github.com/ogen-go/ogen/http"
)

type ApikeyAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *ApikeyAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *ApikeyAuth) SetToken(val string) {
	s.Token = val
}

type BreedsBreedIDFactsGetOK struct{}

// BreedsBreedIDFactsGetOKHeaders wraps BreedsBreedIDFactsGetOK with response headers.
type BreedsBreedIDFactsGetOKHeaders struct {
	ContentLength              OptInt
	Date                       OptString
	Server                     OptString
	XCloudTraceContext         OptString
	AccessControlExposeHeaders OptString
	PaginationCount            OptInt
	PaginationLimit            OptInt
	PaginationPage             OptInt
	RatelimitConsumed          OptInt
	RatelimitLimit             OptInt
	RatelimitRemaining         OptInt
	RatelimitReset             OptFloat64
	RetryAfterSeconds          OptFloat64
	StrictTransportSecurity    OptString
	Vary                       OptString
	XContentTypeOptions        OptString
	XDNSPrefetchControl        OptString
	XDownloadOptions           OptString
	XFrameOptions              OptString
	XResponseTime              OptString
	XXSSProtection             OptString
	Response                   BreedsBreedIDFactsGetOK
}

// GetContentLength returns the value of ContentLength.
func (s *BreedsBreedIDFactsGetOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *BreedsBreedIDFactsGetOKHeaders) GetDate() OptString {
	return s.Date
}

// GetServer returns the value of Server.
func (s *BreedsBreedIDFactsGetOKHeaders) GetServer() OptString {
	return s.Server
}

// GetXCloudTraceContext returns the value of XCloudTraceContext.
func (s *BreedsBreedIDFactsGetOKHeaders) GetXCloudTraceContext() OptString {
	return s.XCloudTraceContext
}

// GetAccessControlExposeHeaders returns the value of AccessControlExposeHeaders.
func (s *BreedsBreedIDFactsGetOKHeaders) GetAccessControlExposeHeaders() OptString {
	return s.AccessControlExposeHeaders
}

// GetPaginationCount returns the value of PaginationCount.
func (s *BreedsBreedIDFactsGetOKHeaders) GetPaginationCount() OptInt {
	return s.PaginationCount
}

// GetPaginationLimit returns the value of PaginationLimit.
func (s *BreedsBreedIDFactsGetOKHeaders) GetPaginationLimit() OptInt {
	return s.PaginationLimit
}

// GetPaginationPage returns the value of PaginationPage.
func (s *BreedsBreedIDFactsGetOKHeaders) GetPaginationPage() OptInt {
	return s.PaginationPage
}

// GetRatelimitConsumed returns the value of RatelimitConsumed.
func (s *BreedsBreedIDFactsGetOKHeaders) GetRatelimitConsumed() OptInt {
	return s.RatelimitConsumed
}

// GetRatelimitLimit returns the value of RatelimitLimit.
func (s *BreedsBreedIDFactsGetOKHeaders) GetRatelimitLimit() OptInt {
	return s.RatelimitLimit
}

// GetRatelimitRemaining returns the value of RatelimitRemaining.
func (s *BreedsBreedIDFactsGetOKHeaders) GetRatelimitRemaining() OptInt {
	return s.RatelimitRemaining
}

// GetRatelimitReset returns the value of RatelimitReset.
func (s *BreedsBreedIDFactsGetOKHeaders) GetRatelimitReset() OptFloat64 {
	return s.RatelimitReset
}

// GetRetryAfterSeconds returns the value of RetryAfterSeconds.
func (s *BreedsBreedIDFactsGetOKHeaders) GetRetryAfterSeconds() OptFloat64 {
	return s.RetryAfterSeconds
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *BreedsBreedIDFactsGetOKHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *BreedsBreedIDFactsGetOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *BreedsBreedIDFactsGetOKHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *BreedsBreedIDFactsGetOKHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *BreedsBreedIDFactsGetOKHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *BreedsBreedIDFactsGetOKHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXResponseTime returns the value of XResponseTime.
func (s *BreedsBreedIDFactsGetOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *BreedsBreedIDFactsGetOKHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *BreedsBreedIDFactsGetOKHeaders) GetResponse() BreedsBreedIDFactsGetOK {
	return s.Response
}

// SetContentLength sets the value of ContentLength.
func (s *BreedsBreedIDFactsGetOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *BreedsBreedIDFactsGetOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetServer sets the value of Server.
func (s *BreedsBreedIDFactsGetOKHeaders) SetServer(val OptString) {
	s.Server = val
}

// SetXCloudTraceContext sets the value of XCloudTraceContext.
func (s *BreedsBreedIDFactsGetOKHeaders) SetXCloudTraceContext(val OptString) {
	s.XCloudTraceContext = val
}

// SetAccessControlExposeHeaders sets the value of AccessControlExposeHeaders.
func (s *BreedsBreedIDFactsGetOKHeaders) SetAccessControlExposeHeaders(val OptString) {
	s.AccessControlExposeHeaders = val
}

// SetPaginationCount sets the value of PaginationCount.
func (s *BreedsBreedIDFactsGetOKHeaders) SetPaginationCount(val OptInt) {
	s.PaginationCount = val
}

// SetPaginationLimit sets the value of PaginationLimit.
func (s *BreedsBreedIDFactsGetOKHeaders) SetPaginationLimit(val OptInt) {
	s.PaginationLimit = val
}

// SetPaginationPage sets the value of PaginationPage.
func (s *BreedsBreedIDFactsGetOKHeaders) SetPaginationPage(val OptInt) {
	s.PaginationPage = val
}

// SetRatelimitConsumed sets the value of RatelimitConsumed.
func (s *BreedsBreedIDFactsGetOKHeaders) SetRatelimitConsumed(val OptInt) {
	s.RatelimitConsumed = val
}

// SetRatelimitLimit sets the value of RatelimitLimit.
func (s *BreedsBreedIDFactsGetOKHeaders) SetRatelimitLimit(val OptInt) {
	s.RatelimitLimit = val
}

// SetRatelimitRemaining sets the value of RatelimitRemaining.
func (s *BreedsBreedIDFactsGetOKHeaders) SetRatelimitRemaining(val OptInt) {
	s.RatelimitRemaining = val
}

// SetRatelimitReset sets the value of RatelimitReset.
func (s *BreedsBreedIDFactsGetOKHeaders) SetRatelimitReset(val OptFloat64) {
	s.RatelimitReset = val
}

// SetRetryAfterSeconds sets the value of RetryAfterSeconds.
func (s *BreedsBreedIDFactsGetOKHeaders) SetRetryAfterSeconds(val OptFloat64) {
	s.RetryAfterSeconds = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *BreedsBreedIDFactsGetOKHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *BreedsBreedIDFactsGetOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *BreedsBreedIDFactsGetOKHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *BreedsBreedIDFactsGetOKHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *BreedsBreedIDFactsGetOKHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *BreedsBreedIDFactsGetOKHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *BreedsBreedIDFactsGetOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *BreedsBreedIDFactsGetOKHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *BreedsBreedIDFactsGetOKHeaders) SetResponse(val BreedsBreedIDFactsGetOK) {
	s.Response = val
}

type BreedsBreedIDGetOK struct{}

// BreedsBreedIDGetOKHeaders wraps BreedsBreedIDGetOK with response headers.
type BreedsBreedIDGetOKHeaders struct {
	Connection    OptString
	ContentLength OptInt
	Date          OptString
	Vary          OptString
	XResponseTime OptString
	Response      BreedsBreedIDGetOK
}

// GetConnection returns the value of Connection.
func (s *BreedsBreedIDGetOKHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *BreedsBreedIDGetOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *BreedsBreedIDGetOKHeaders) GetDate() OptString {
	return s.Date
}

// GetVary returns the value of Vary.
func (s *BreedsBreedIDGetOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXResponseTime returns the value of XResponseTime.
func (s *BreedsBreedIDGetOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetResponse returns the value of Response.
func (s *BreedsBreedIDGetOKHeaders) GetResponse() BreedsBreedIDGetOK {
	return s.Response
}

// SetConnection sets the value of Connection.
func (s *BreedsBreedIDGetOKHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *BreedsBreedIDGetOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *BreedsBreedIDGetOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetVary sets the value of Vary.
func (s *BreedsBreedIDGetOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *BreedsBreedIDGetOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetResponse sets the value of Response.
func (s *BreedsBreedIDGetOKHeaders) SetResponse(val BreedsBreedIDGetOK) {
	s.Response = val
}

type BreedsGetOK struct{}

// BreedsGetOKHeaders wraps BreedsGetOK with response headers.
type BreedsGetOKHeaders struct {
	AccessControlExposeHeaders OptString
	Connection                 OptString
	ContentLength              OptInt
	Date                       OptString
	KeepAlive                  OptString
	PaginationCount            OptInt
	PaginationLimit            OptInt
	PaginationPage             OptInt
	RateLimitConsumed          OptInt
	RateLimitLimit             OptInt
	RateLimitRemaining         OptInt
	RateLimitReset             OptFloat64
	RetryAfterSeconds          OptFloat64
	StrictTransportSecurity    OptString
	Vary                       OptString
	XContentTypeOptions        OptString
	XDNSPrefetchControl        OptString
	XDownloadOptions           OptString
	XFrameOptions              OptString
	XResponseTime              OptString
	XXSSProtection             OptString
	Response                   BreedsGetOK
}

// GetAccessControlExposeHeaders returns the value of AccessControlExposeHeaders.
func (s *BreedsGetOKHeaders) GetAccessControlExposeHeaders() OptString {
	return s.AccessControlExposeHeaders
}

// GetConnection returns the value of Connection.
func (s *BreedsGetOKHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *BreedsGetOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *BreedsGetOKHeaders) GetDate() OptString {
	return s.Date
}

// GetKeepAlive returns the value of KeepAlive.
func (s *BreedsGetOKHeaders) GetKeepAlive() OptString {
	return s.KeepAlive
}

// GetPaginationCount returns the value of PaginationCount.
func (s *BreedsGetOKHeaders) GetPaginationCount() OptInt {
	return s.PaginationCount
}

// GetPaginationLimit returns the value of PaginationLimit.
func (s *BreedsGetOKHeaders) GetPaginationLimit() OptInt {
	return s.PaginationLimit
}

// GetPaginationPage returns the value of PaginationPage.
func (s *BreedsGetOKHeaders) GetPaginationPage() OptInt {
	return s.PaginationPage
}

// GetRateLimitConsumed returns the value of RateLimitConsumed.
func (s *BreedsGetOKHeaders) GetRateLimitConsumed() OptInt {
	return s.RateLimitConsumed
}

// GetRateLimitLimit returns the value of RateLimitLimit.
func (s *BreedsGetOKHeaders) GetRateLimitLimit() OptInt {
	return s.RateLimitLimit
}

// GetRateLimitRemaining returns the value of RateLimitRemaining.
func (s *BreedsGetOKHeaders) GetRateLimitRemaining() OptInt {
	return s.RateLimitRemaining
}

// GetRateLimitReset returns the value of RateLimitReset.
func (s *BreedsGetOKHeaders) GetRateLimitReset() OptFloat64 {
	return s.RateLimitReset
}

// GetRetryAfterSeconds returns the value of RetryAfterSeconds.
func (s *BreedsGetOKHeaders) GetRetryAfterSeconds() OptFloat64 {
	return s.RetryAfterSeconds
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *BreedsGetOKHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *BreedsGetOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *BreedsGetOKHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *BreedsGetOKHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *BreedsGetOKHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *BreedsGetOKHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXResponseTime returns the value of XResponseTime.
func (s *BreedsGetOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *BreedsGetOKHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *BreedsGetOKHeaders) GetResponse() BreedsGetOK {
	return s.Response
}

// SetAccessControlExposeHeaders sets the value of AccessControlExposeHeaders.
func (s *BreedsGetOKHeaders) SetAccessControlExposeHeaders(val OptString) {
	s.AccessControlExposeHeaders = val
}

// SetConnection sets the value of Connection.
func (s *BreedsGetOKHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *BreedsGetOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *BreedsGetOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetKeepAlive sets the value of KeepAlive.
func (s *BreedsGetOKHeaders) SetKeepAlive(val OptString) {
	s.KeepAlive = val
}

// SetPaginationCount sets the value of PaginationCount.
func (s *BreedsGetOKHeaders) SetPaginationCount(val OptInt) {
	s.PaginationCount = val
}

// SetPaginationLimit sets the value of PaginationLimit.
func (s *BreedsGetOKHeaders) SetPaginationLimit(val OptInt) {
	s.PaginationLimit = val
}

// SetPaginationPage sets the value of PaginationPage.
func (s *BreedsGetOKHeaders) SetPaginationPage(val OptInt) {
	s.PaginationPage = val
}

// SetRateLimitConsumed sets the value of RateLimitConsumed.
func (s *BreedsGetOKHeaders) SetRateLimitConsumed(val OptInt) {
	s.RateLimitConsumed = val
}

// SetRateLimitLimit sets the value of RateLimitLimit.
func (s *BreedsGetOKHeaders) SetRateLimitLimit(val OptInt) {
	s.RateLimitLimit = val
}

// SetRateLimitRemaining sets the value of RateLimitRemaining.
func (s *BreedsGetOKHeaders) SetRateLimitRemaining(val OptInt) {
	s.RateLimitRemaining = val
}

// SetRateLimitReset sets the value of RateLimitReset.
func (s *BreedsGetOKHeaders) SetRateLimitReset(val OptFloat64) {
	s.RateLimitReset = val
}

// SetRetryAfterSeconds sets the value of RetryAfterSeconds.
func (s *BreedsGetOKHeaders) SetRetryAfterSeconds(val OptFloat64) {
	s.RetryAfterSeconds = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *BreedsGetOKHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *BreedsGetOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *BreedsGetOKHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *BreedsGetOKHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *BreedsGetOKHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *BreedsGetOKHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *BreedsGetOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *BreedsGetOKHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *BreedsGetOKHeaders) SetResponse(val BreedsGetOK) {
	s.Response = val
}

type BreedsSearchGetOK struct{}

// BreedsSearchGetOKHeaders wraps BreedsSearchGetOK with response headers.
type BreedsSearchGetOKHeaders struct {
	Connection              OptString
	ContentLength           OptInt
	Date                    OptString
	KeepAlive               OptString
	RateLimitConsumed       OptInt
	RateLimitLimit          OptInt
	RateLimitRemaining      OptInt
	RateLimitReset          OptFloat64
	RetryAfterSeconds       OptInt
	StrictTransportSecurity OptString
	Vary                    OptString
	XContentTypeOptions     OptString
	XDNSPrefetchControl     OptString
	XDownloadOptions        OptString
	XFrameOptions           OptString
	XResponseTime           OptString
	XXSSProtection          OptString
	Response                BreedsSearchGetOK
}

// GetConnection returns the value of Connection.
func (s *BreedsSearchGetOKHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *BreedsSearchGetOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *BreedsSearchGetOKHeaders) GetDate() OptString {
	return s.Date
}

// GetKeepAlive returns the value of KeepAlive.
func (s *BreedsSearchGetOKHeaders) GetKeepAlive() OptString {
	return s.KeepAlive
}

// GetRateLimitConsumed returns the value of RateLimitConsumed.
func (s *BreedsSearchGetOKHeaders) GetRateLimitConsumed() OptInt {
	return s.RateLimitConsumed
}

// GetRateLimitLimit returns the value of RateLimitLimit.
func (s *BreedsSearchGetOKHeaders) GetRateLimitLimit() OptInt {
	return s.RateLimitLimit
}

// GetRateLimitRemaining returns the value of RateLimitRemaining.
func (s *BreedsSearchGetOKHeaders) GetRateLimitRemaining() OptInt {
	return s.RateLimitRemaining
}

// GetRateLimitReset returns the value of RateLimitReset.
func (s *BreedsSearchGetOKHeaders) GetRateLimitReset() OptFloat64 {
	return s.RateLimitReset
}

// GetRetryAfterSeconds returns the value of RetryAfterSeconds.
func (s *BreedsSearchGetOKHeaders) GetRetryAfterSeconds() OptInt {
	return s.RetryAfterSeconds
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *BreedsSearchGetOKHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *BreedsSearchGetOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *BreedsSearchGetOKHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *BreedsSearchGetOKHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *BreedsSearchGetOKHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *BreedsSearchGetOKHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXResponseTime returns the value of XResponseTime.
func (s *BreedsSearchGetOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *BreedsSearchGetOKHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *BreedsSearchGetOKHeaders) GetResponse() BreedsSearchGetOK {
	return s.Response
}

// SetConnection sets the value of Connection.
func (s *BreedsSearchGetOKHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *BreedsSearchGetOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *BreedsSearchGetOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetKeepAlive sets the value of KeepAlive.
func (s *BreedsSearchGetOKHeaders) SetKeepAlive(val OptString) {
	s.KeepAlive = val
}

// SetRateLimitConsumed sets the value of RateLimitConsumed.
func (s *BreedsSearchGetOKHeaders) SetRateLimitConsumed(val OptInt) {
	s.RateLimitConsumed = val
}

// SetRateLimitLimit sets the value of RateLimitLimit.
func (s *BreedsSearchGetOKHeaders) SetRateLimitLimit(val OptInt) {
	s.RateLimitLimit = val
}

// SetRateLimitRemaining sets the value of RateLimitRemaining.
func (s *BreedsSearchGetOKHeaders) SetRateLimitRemaining(val OptInt) {
	s.RateLimitRemaining = val
}

// SetRateLimitReset sets the value of RateLimitReset.
func (s *BreedsSearchGetOKHeaders) SetRateLimitReset(val OptFloat64) {
	s.RateLimitReset = val
}

// SetRetryAfterSeconds sets the value of RetryAfterSeconds.
func (s *BreedsSearchGetOKHeaders) SetRetryAfterSeconds(val OptInt) {
	s.RetryAfterSeconds = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *BreedsSearchGetOKHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *BreedsSearchGetOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *BreedsSearchGetOKHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *BreedsSearchGetOKHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *BreedsSearchGetOKHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *BreedsSearchGetOKHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *BreedsSearchGetOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *BreedsSearchGetOKHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *BreedsSearchGetOKHeaders) SetResponse(val BreedsSearchGetOK) {
	s.Response = val
}

type FactsGetOK struct{}

// FactsGetOKHeaders wraps FactsGetOK with response headers.
type FactsGetOKHeaders struct {
	ContentLength              OptInt
	Date                       OptString
	Server                     OptString
	XCloudTraceContext         OptString
	AccessControlExposeHeaders OptString
	PaginationCount            OptInt
	PaginationLimit            OptInt
	PaginationPage             OptInt
	StrictTransportSecurity    OptString
	Vary                       OptString
	XContentTypeOptions        OptString
	XDNSPrefetchControl        OptString
	XDownloadOptions           OptString
	XFrameOptions              OptString
	XResponseTime              OptString
	XXSSProtection             OptString
	Response                   FactsGetOK
}

// GetContentLength returns the value of ContentLength.
func (s *FactsGetOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *FactsGetOKHeaders) GetDate() OptString {
	return s.Date
}

// GetServer returns the value of Server.
func (s *FactsGetOKHeaders) GetServer() OptString {
	return s.Server
}

// GetXCloudTraceContext returns the value of XCloudTraceContext.
func (s *FactsGetOKHeaders) GetXCloudTraceContext() OptString {
	return s.XCloudTraceContext
}

// GetAccessControlExposeHeaders returns the value of AccessControlExposeHeaders.
func (s *FactsGetOKHeaders) GetAccessControlExposeHeaders() OptString {
	return s.AccessControlExposeHeaders
}

// GetPaginationCount returns the value of PaginationCount.
func (s *FactsGetOKHeaders) GetPaginationCount() OptInt {
	return s.PaginationCount
}

// GetPaginationLimit returns the value of PaginationLimit.
func (s *FactsGetOKHeaders) GetPaginationLimit() OptInt {
	return s.PaginationLimit
}

// GetPaginationPage returns the value of PaginationPage.
func (s *FactsGetOKHeaders) GetPaginationPage() OptInt {
	return s.PaginationPage
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *FactsGetOKHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *FactsGetOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *FactsGetOKHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *FactsGetOKHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *FactsGetOKHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *FactsGetOKHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXResponseTime returns the value of XResponseTime.
func (s *FactsGetOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *FactsGetOKHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *FactsGetOKHeaders) GetResponse() FactsGetOK {
	return s.Response
}

// SetContentLength sets the value of ContentLength.
func (s *FactsGetOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *FactsGetOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetServer sets the value of Server.
func (s *FactsGetOKHeaders) SetServer(val OptString) {
	s.Server = val
}

// SetXCloudTraceContext sets the value of XCloudTraceContext.
func (s *FactsGetOKHeaders) SetXCloudTraceContext(val OptString) {
	s.XCloudTraceContext = val
}

// SetAccessControlExposeHeaders sets the value of AccessControlExposeHeaders.
func (s *FactsGetOKHeaders) SetAccessControlExposeHeaders(val OptString) {
	s.AccessControlExposeHeaders = val
}

// SetPaginationCount sets the value of PaginationCount.
func (s *FactsGetOKHeaders) SetPaginationCount(val OptInt) {
	s.PaginationCount = val
}

// SetPaginationLimit sets the value of PaginationLimit.
func (s *FactsGetOKHeaders) SetPaginationLimit(val OptInt) {
	s.PaginationLimit = val
}

// SetPaginationPage sets the value of PaginationPage.
func (s *FactsGetOKHeaders) SetPaginationPage(val OptInt) {
	s.PaginationPage = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *FactsGetOKHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *FactsGetOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *FactsGetOKHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *FactsGetOKHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *FactsGetOKHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *FactsGetOKHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *FactsGetOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *FactsGetOKHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *FactsGetOKHeaders) SetResponse(val FactsGetOK) {
	s.Response = val
}

type FavouritesGetOK struct{}

// FavouritesGetOKHeaders wraps FavouritesGetOK with response headers.
type FavouritesGetOKHeaders struct {
	AccessControlExposeHeaders OptString
	Connection                 OptString
	ContentLength              OptInt
	Date                       OptString
	KeepAlive                  OptString
	PaginationCount            OptInt
	PaginationLimit            OptInt
	PaginationPage             OptInt
	RateLimitConsumed          OptInt
	RateLimitLimit             OptInt
	RateLimitRemaining         OptInt
	RateLimitReset             OptFloat64
	RetryAfterSeconds          OptFloat64
	StrictTransportSecurity    OptString
	Vary                       OptString
	XContentTypeOptions        OptString
	XDNSPrefetchControl        OptString
	XDownloadOptions           OptString
	XFrameOptions              OptString
	XResponseTime              OptString
	XXSSProtection             OptString
	Response                   FavouritesGetOK
}

// GetAccessControlExposeHeaders returns the value of AccessControlExposeHeaders.
func (s *FavouritesGetOKHeaders) GetAccessControlExposeHeaders() OptString {
	return s.AccessControlExposeHeaders
}

// GetConnection returns the value of Connection.
func (s *FavouritesGetOKHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *FavouritesGetOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *FavouritesGetOKHeaders) GetDate() OptString {
	return s.Date
}

// GetKeepAlive returns the value of KeepAlive.
func (s *FavouritesGetOKHeaders) GetKeepAlive() OptString {
	return s.KeepAlive
}

// GetPaginationCount returns the value of PaginationCount.
func (s *FavouritesGetOKHeaders) GetPaginationCount() OptInt {
	return s.PaginationCount
}

// GetPaginationLimit returns the value of PaginationLimit.
func (s *FavouritesGetOKHeaders) GetPaginationLimit() OptInt {
	return s.PaginationLimit
}

// GetPaginationPage returns the value of PaginationPage.
func (s *FavouritesGetOKHeaders) GetPaginationPage() OptInt {
	return s.PaginationPage
}

// GetRateLimitConsumed returns the value of RateLimitConsumed.
func (s *FavouritesGetOKHeaders) GetRateLimitConsumed() OptInt {
	return s.RateLimitConsumed
}

// GetRateLimitLimit returns the value of RateLimitLimit.
func (s *FavouritesGetOKHeaders) GetRateLimitLimit() OptInt {
	return s.RateLimitLimit
}

// GetRateLimitRemaining returns the value of RateLimitRemaining.
func (s *FavouritesGetOKHeaders) GetRateLimitRemaining() OptInt {
	return s.RateLimitRemaining
}

// GetRateLimitReset returns the value of RateLimitReset.
func (s *FavouritesGetOKHeaders) GetRateLimitReset() OptFloat64 {
	return s.RateLimitReset
}

// GetRetryAfterSeconds returns the value of RetryAfterSeconds.
func (s *FavouritesGetOKHeaders) GetRetryAfterSeconds() OptFloat64 {
	return s.RetryAfterSeconds
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *FavouritesGetOKHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *FavouritesGetOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *FavouritesGetOKHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *FavouritesGetOKHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *FavouritesGetOKHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *FavouritesGetOKHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXResponseTime returns the value of XResponseTime.
func (s *FavouritesGetOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *FavouritesGetOKHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *FavouritesGetOKHeaders) GetResponse() FavouritesGetOK {
	return s.Response
}

// SetAccessControlExposeHeaders sets the value of AccessControlExposeHeaders.
func (s *FavouritesGetOKHeaders) SetAccessControlExposeHeaders(val OptString) {
	s.AccessControlExposeHeaders = val
}

// SetConnection sets the value of Connection.
func (s *FavouritesGetOKHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *FavouritesGetOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *FavouritesGetOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetKeepAlive sets the value of KeepAlive.
func (s *FavouritesGetOKHeaders) SetKeepAlive(val OptString) {
	s.KeepAlive = val
}

// SetPaginationCount sets the value of PaginationCount.
func (s *FavouritesGetOKHeaders) SetPaginationCount(val OptInt) {
	s.PaginationCount = val
}

// SetPaginationLimit sets the value of PaginationLimit.
func (s *FavouritesGetOKHeaders) SetPaginationLimit(val OptInt) {
	s.PaginationLimit = val
}

// SetPaginationPage sets the value of PaginationPage.
func (s *FavouritesGetOKHeaders) SetPaginationPage(val OptInt) {
	s.PaginationPage = val
}

// SetRateLimitConsumed sets the value of RateLimitConsumed.
func (s *FavouritesGetOKHeaders) SetRateLimitConsumed(val OptInt) {
	s.RateLimitConsumed = val
}

// SetRateLimitLimit sets the value of RateLimitLimit.
func (s *FavouritesGetOKHeaders) SetRateLimitLimit(val OptInt) {
	s.RateLimitLimit = val
}

// SetRateLimitRemaining sets the value of RateLimitRemaining.
func (s *FavouritesGetOKHeaders) SetRateLimitRemaining(val OptInt) {
	s.RateLimitRemaining = val
}

// SetRateLimitReset sets the value of RateLimitReset.
func (s *FavouritesGetOKHeaders) SetRateLimitReset(val OptFloat64) {
	s.RateLimitReset = val
}

// SetRetryAfterSeconds sets the value of RetryAfterSeconds.
func (s *FavouritesGetOKHeaders) SetRetryAfterSeconds(val OptFloat64) {
	s.RetryAfterSeconds = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *FavouritesGetOKHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *FavouritesGetOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *FavouritesGetOKHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *FavouritesGetOKHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *FavouritesGetOKHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *FavouritesGetOKHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *FavouritesGetOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *FavouritesGetOKHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *FavouritesGetOKHeaders) SetResponse(val FavouritesGetOK) {
	s.Response = val
}

type FavouritesPostOK struct{}

// FavouritesPostOKHeaders wraps FavouritesPostOK with response headers.
type FavouritesPostOKHeaders struct {
	Connection              OptString
	ContentLength           OptInt
	Date                    OptString
	KeepAlive               OptString
	RateLimitConsumed       OptInt
	RateLimitLimit          OptInt
	RateLimitRemaining      OptInt
	RateLimitReset          OptFloat64
	RetryAfterSeconds       OptFloat64
	StrictTransportSecurity OptString
	Vary                    OptString
	XContentTypeOptions     OptString
	XDNSPrefetchControl     OptString
	XDownloadOptions        OptString
	XFrameOptions           OptString
	XResponseTime           OptString
	XXSSProtection          OptString
	Response                FavouritesPostOK
}

// GetConnection returns the value of Connection.
func (s *FavouritesPostOKHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *FavouritesPostOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *FavouritesPostOKHeaders) GetDate() OptString {
	return s.Date
}

// GetKeepAlive returns the value of KeepAlive.
func (s *FavouritesPostOKHeaders) GetKeepAlive() OptString {
	return s.KeepAlive
}

// GetRateLimitConsumed returns the value of RateLimitConsumed.
func (s *FavouritesPostOKHeaders) GetRateLimitConsumed() OptInt {
	return s.RateLimitConsumed
}

// GetRateLimitLimit returns the value of RateLimitLimit.
func (s *FavouritesPostOKHeaders) GetRateLimitLimit() OptInt {
	return s.RateLimitLimit
}

// GetRateLimitRemaining returns the value of RateLimitRemaining.
func (s *FavouritesPostOKHeaders) GetRateLimitRemaining() OptInt {
	return s.RateLimitRemaining
}

// GetRateLimitReset returns the value of RateLimitReset.
func (s *FavouritesPostOKHeaders) GetRateLimitReset() OptFloat64 {
	return s.RateLimitReset
}

// GetRetryAfterSeconds returns the value of RetryAfterSeconds.
func (s *FavouritesPostOKHeaders) GetRetryAfterSeconds() OptFloat64 {
	return s.RetryAfterSeconds
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *FavouritesPostOKHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *FavouritesPostOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *FavouritesPostOKHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *FavouritesPostOKHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *FavouritesPostOKHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *FavouritesPostOKHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXResponseTime returns the value of XResponseTime.
func (s *FavouritesPostOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *FavouritesPostOKHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *FavouritesPostOKHeaders) GetResponse() FavouritesPostOK {
	return s.Response
}

// SetConnection sets the value of Connection.
func (s *FavouritesPostOKHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *FavouritesPostOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *FavouritesPostOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetKeepAlive sets the value of KeepAlive.
func (s *FavouritesPostOKHeaders) SetKeepAlive(val OptString) {
	s.KeepAlive = val
}

// SetRateLimitConsumed sets the value of RateLimitConsumed.
func (s *FavouritesPostOKHeaders) SetRateLimitConsumed(val OptInt) {
	s.RateLimitConsumed = val
}

// SetRateLimitLimit sets the value of RateLimitLimit.
func (s *FavouritesPostOKHeaders) SetRateLimitLimit(val OptInt) {
	s.RateLimitLimit = val
}

// SetRateLimitRemaining sets the value of RateLimitRemaining.
func (s *FavouritesPostOKHeaders) SetRateLimitRemaining(val OptInt) {
	s.RateLimitRemaining = val
}

// SetRateLimitReset sets the value of RateLimitReset.
func (s *FavouritesPostOKHeaders) SetRateLimitReset(val OptFloat64) {
	s.RateLimitReset = val
}

// SetRetryAfterSeconds sets the value of RetryAfterSeconds.
func (s *FavouritesPostOKHeaders) SetRetryAfterSeconds(val OptFloat64) {
	s.RetryAfterSeconds = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *FavouritesPostOKHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *FavouritesPostOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *FavouritesPostOKHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *FavouritesPostOKHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *FavouritesPostOKHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *FavouritesPostOKHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *FavouritesPostOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *FavouritesPostOKHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *FavouritesPostOKHeaders) SetResponse(val FavouritesPostOK) {
	s.Response = val
}

type FavouritesPostReq struct{}

type ImagesBkIEhN3pGGetOK struct{}

// ImagesBkIEhN3pGGetOKHeaders wraps ImagesBkIEhN3pGGetOK with response headers.
type ImagesBkIEhN3pGGetOKHeaders struct {
	Connection              OptString
	ContentLength           OptInt
	Date                    OptString
	KeepAlive               OptString
	StrictTransportSecurity OptString
	Vary                    OptString
	XContentTypeOptions     OptString
	XDNSPrefetchControl     OptString
	XDownloadOptions        OptString
	XFrameOptions           OptString
	XResponseTime           OptString
	XXSSProtection          OptString
	Response                ImagesBkIEhN3pGGetOK
}

// GetConnection returns the value of Connection.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetDate() OptString {
	return s.Date
}

// GetKeepAlive returns the value of KeepAlive.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetKeepAlive() OptString {
	return s.KeepAlive
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXResponseTime returns the value of XResponseTime.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *ImagesBkIEhN3pGGetOKHeaders) GetResponse() ImagesBkIEhN3pGGetOK {
	return s.Response
}

// SetConnection sets the value of Connection.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetKeepAlive sets the value of KeepAlive.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetKeepAlive(val OptString) {
	s.KeepAlive = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *ImagesBkIEhN3pGGetOKHeaders) SetResponse(val ImagesBkIEhN3pGGetOK) {
	s.Response = val
}

type ImagesGetOK struct{}

// ImagesGetOKHeaders wraps ImagesGetOK with response headers.
type ImagesGetOKHeaders struct {
	Connection    OptString
	ContentLength OptInt
	Date          OptString
	Vary          OptString
	XResponseTime OptString
	Response      ImagesGetOK
}

// GetConnection returns the value of Connection.
func (s *ImagesGetOKHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *ImagesGetOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *ImagesGetOKHeaders) GetDate() OptString {
	return s.Date
}

// GetVary returns the value of Vary.
func (s *ImagesGetOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXResponseTime returns the value of XResponseTime.
func (s *ImagesGetOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetResponse returns the value of Response.
func (s *ImagesGetOKHeaders) GetResponse() ImagesGetOK {
	return s.Response
}

// SetConnection sets the value of Connection.
func (s *ImagesGetOKHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *ImagesGetOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *ImagesGetOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetVary sets the value of Vary.
func (s *ImagesGetOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *ImagesGetOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetResponse sets the value of Response.
func (s *ImagesGetOKHeaders) SetResponse(val ImagesGetOK) {
	s.Response = val
}

type ImagesSearchGetOK struct{}

// ImagesSearchGetOKHeaders wraps ImagesSearchGetOK with response headers.
type ImagesSearchGetOKHeaders struct {
	CacheControl  OptString
	Connection    OptString
	ContentLength OptInt
	Date          OptString
	Expires       OptString
	LastModified  OptString
	Vary          OptString
	XResponseTime OptString
	Response      ImagesSearchGetOK
}

// GetCacheControl returns the value of CacheControl.
func (s *ImagesSearchGetOKHeaders) GetCacheControl() OptString {
	return s.CacheControl
}

// GetConnection returns the value of Connection.
func (s *ImagesSearchGetOKHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *ImagesSearchGetOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *ImagesSearchGetOKHeaders) GetDate() OptString {
	return s.Date
}

// GetExpires returns the value of Expires.
func (s *ImagesSearchGetOKHeaders) GetExpires() OptString {
	return s.Expires
}

// GetLastModified returns the value of LastModified.
func (s *ImagesSearchGetOKHeaders) GetLastModified() OptString {
	return s.LastModified
}

// GetVary returns the value of Vary.
func (s *ImagesSearchGetOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXResponseTime returns the value of XResponseTime.
func (s *ImagesSearchGetOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetResponse returns the value of Response.
func (s *ImagesSearchGetOKHeaders) GetResponse() ImagesSearchGetOK {
	return s.Response
}

// SetCacheControl sets the value of CacheControl.
func (s *ImagesSearchGetOKHeaders) SetCacheControl(val OptString) {
	s.CacheControl = val
}

// SetConnection sets the value of Connection.
func (s *ImagesSearchGetOKHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *ImagesSearchGetOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *ImagesSearchGetOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetExpires sets the value of Expires.
func (s *ImagesSearchGetOKHeaders) SetExpires(val OptString) {
	s.Expires = val
}

// SetLastModified sets the value of LastModified.
func (s *ImagesSearchGetOKHeaders) SetLastModified(val OptString) {
	s.LastModified = val
}

// SetVary sets the value of Vary.
func (s *ImagesSearchGetOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *ImagesSearchGetOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetResponse sets the value of Response.
func (s *ImagesSearchGetOKHeaders) SetResponse(val ImagesSearchGetOK) {
	s.Response = val
}

func (*ImagesSearchGetOKHeaders) imagesSearchGetRes() {}

type ImagesSearchGetUnauthorized struct{}

// ImagesSearchGetUnauthorizedHeaders wraps ImagesSearchGetUnauthorized with response headers.
type ImagesSearchGetUnauthorizedHeaders struct {
	Connection              OptString
	ContentLength           OptInt
	Date                    OptString
	Server                  OptFloat64
	StrictTransportSecurity OptString
	Vary                    OptString
	XContentTypeOptions     OptString
	XDNSPrefetchControl     OptString
	XDownloadOptions        OptString
	XFrameOptions           OptString
	XXSSProtection          OptString
	Response                ImagesSearchGetUnauthorized
}

// GetConnection returns the value of Connection.
func (s *ImagesSearchGetUnauthorizedHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *ImagesSearchGetUnauthorizedHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *ImagesSearchGetUnauthorizedHeaders) GetDate() OptString {
	return s.Date
}

// GetServer returns the value of Server.
func (s *ImagesSearchGetUnauthorizedHeaders) GetServer() OptFloat64 {
	return s.Server
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *ImagesSearchGetUnauthorizedHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *ImagesSearchGetUnauthorizedHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *ImagesSearchGetUnauthorizedHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *ImagesSearchGetUnauthorizedHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *ImagesSearchGetUnauthorizedHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *ImagesSearchGetUnauthorizedHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *ImagesSearchGetUnauthorizedHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *ImagesSearchGetUnauthorizedHeaders) GetResponse() ImagesSearchGetUnauthorized {
	return s.Response
}

// SetConnection sets the value of Connection.
func (s *ImagesSearchGetUnauthorizedHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *ImagesSearchGetUnauthorizedHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *ImagesSearchGetUnauthorizedHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetServer sets the value of Server.
func (s *ImagesSearchGetUnauthorizedHeaders) SetServer(val OptFloat64) {
	s.Server = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *ImagesSearchGetUnauthorizedHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *ImagesSearchGetUnauthorizedHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *ImagesSearchGetUnauthorizedHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *ImagesSearchGetUnauthorizedHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *ImagesSearchGetUnauthorizedHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *ImagesSearchGetUnauthorizedHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *ImagesSearchGetUnauthorizedHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *ImagesSearchGetUnauthorizedHeaders) SetResponse(val ImagesSearchGetUnauthorized) {
	s.Response = val
}

func (*ImagesSearchGetUnauthorizedHeaders) imagesSearchGetRes() {}

type ImagesUploadPostCreated struct{}

// ImagesUploadPostCreatedHeaders wraps ImagesUploadPostCreated with response headers.
type ImagesUploadPostCreatedHeaders struct {
	Connection              OptString
	ContentLength           OptInt
	Date                    OptString
	KeepAlive               OptString
	RateLimitConsumed       OptInt
	RateLimitLimit          OptInt
	RateLimitRemaining      OptInt
	RateLimitReset          OptFloat64
	RetryAfterSeconds       OptInt
	StrictTransportSecurity OptString
	Vary                    OptString
	XContentTypeOptions     OptString
	XDNSPrefetchControl     OptString
	XDownloadOptions        OptString
	XFrameOptions           OptString
	XResponseTime           OptString
	XXSSProtection          OptString
	Response                ImagesUploadPostCreated
}

// GetConnection returns the value of Connection.
func (s *ImagesUploadPostCreatedHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *ImagesUploadPostCreatedHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *ImagesUploadPostCreatedHeaders) GetDate() OptString {
	return s.Date
}

// GetKeepAlive returns the value of KeepAlive.
func (s *ImagesUploadPostCreatedHeaders) GetKeepAlive() OptString {
	return s.KeepAlive
}

// GetRateLimitConsumed returns the value of RateLimitConsumed.
func (s *ImagesUploadPostCreatedHeaders) GetRateLimitConsumed() OptInt {
	return s.RateLimitConsumed
}

// GetRateLimitLimit returns the value of RateLimitLimit.
func (s *ImagesUploadPostCreatedHeaders) GetRateLimitLimit() OptInt {
	return s.RateLimitLimit
}

// GetRateLimitRemaining returns the value of RateLimitRemaining.
func (s *ImagesUploadPostCreatedHeaders) GetRateLimitRemaining() OptInt {
	return s.RateLimitRemaining
}

// GetRateLimitReset returns the value of RateLimitReset.
func (s *ImagesUploadPostCreatedHeaders) GetRateLimitReset() OptFloat64 {
	return s.RateLimitReset
}

// GetRetryAfterSeconds returns the value of RetryAfterSeconds.
func (s *ImagesUploadPostCreatedHeaders) GetRetryAfterSeconds() OptInt {
	return s.RetryAfterSeconds
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *ImagesUploadPostCreatedHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *ImagesUploadPostCreatedHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *ImagesUploadPostCreatedHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *ImagesUploadPostCreatedHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *ImagesUploadPostCreatedHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *ImagesUploadPostCreatedHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXResponseTime returns the value of XResponseTime.
func (s *ImagesUploadPostCreatedHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *ImagesUploadPostCreatedHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *ImagesUploadPostCreatedHeaders) GetResponse() ImagesUploadPostCreated {
	return s.Response
}

// SetConnection sets the value of Connection.
func (s *ImagesUploadPostCreatedHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *ImagesUploadPostCreatedHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *ImagesUploadPostCreatedHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetKeepAlive sets the value of KeepAlive.
func (s *ImagesUploadPostCreatedHeaders) SetKeepAlive(val OptString) {
	s.KeepAlive = val
}

// SetRateLimitConsumed sets the value of RateLimitConsumed.
func (s *ImagesUploadPostCreatedHeaders) SetRateLimitConsumed(val OptInt) {
	s.RateLimitConsumed = val
}

// SetRateLimitLimit sets the value of RateLimitLimit.
func (s *ImagesUploadPostCreatedHeaders) SetRateLimitLimit(val OptInt) {
	s.RateLimitLimit = val
}

// SetRateLimitRemaining sets the value of RateLimitRemaining.
func (s *ImagesUploadPostCreatedHeaders) SetRateLimitRemaining(val OptInt) {
	s.RateLimitRemaining = val
}

// SetRateLimitReset sets the value of RateLimitReset.
func (s *ImagesUploadPostCreatedHeaders) SetRateLimitReset(val OptFloat64) {
	s.RateLimitReset = val
}

// SetRetryAfterSeconds sets the value of RetryAfterSeconds.
func (s *ImagesUploadPostCreatedHeaders) SetRetryAfterSeconds(val OptInt) {
	s.RetryAfterSeconds = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *ImagesUploadPostCreatedHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *ImagesUploadPostCreatedHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *ImagesUploadPostCreatedHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *ImagesUploadPostCreatedHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *ImagesUploadPostCreatedHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *ImagesUploadPostCreatedHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *ImagesUploadPostCreatedHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *ImagesUploadPostCreatedHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *ImagesUploadPostCreatedHeaders) SetResponse(val ImagesUploadPostCreated) {
	s.Response = val
}

type ImagesUploadPostReq struct {
	File OptMultipartFile `json:"file"`
	// [optional] - a string you can use to segment your images, e.g. knowing which of your own users
	// uploaded it.
	SubID OptString `json:"sub_id"`
	// [optional] comma separated string of breed ids contained in the image.
	BreedIds OptString `json:"breed_ids"`
}

// GetFile returns the value of File.
func (s *ImagesUploadPostReq) GetFile() OptMultipartFile {
	return s.File
}

// GetSubID returns the value of SubID.
func (s *ImagesUploadPostReq) GetSubID() OptString {
	return s.SubID
}

// GetBreedIds returns the value of BreedIds.
func (s *ImagesUploadPostReq) GetBreedIds() OptString {
	return s.BreedIds
}

// SetFile sets the value of File.
func (s *ImagesUploadPostReq) SetFile(val OptMultipartFile) {
	s.File = val
}

// SetSubID sets the value of SubID.
func (s *ImagesUploadPostReq) SetSubID(val OptString) {
	s.SubID = val
}

// SetBreedIds sets the value of BreedIds.
func (s *ImagesUploadPostReq) SetBreedIds(val OptString) {
	s.BreedIds = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptImagesUploadPostReq returns new OptImagesUploadPostReq with value set to v.
func NewOptImagesUploadPostReq(v ImagesUploadPostReq) OptImagesUploadPostReq {
	return OptImagesUploadPostReq{
		Value: v,
		Set:   true,
	}
}

// OptImagesUploadPostReq is optional ImagesUploadPostReq.
type OptImagesUploadPostReq struct {
	Value ImagesUploadPostReq
	Set   bool
}

// IsSet returns true if OptImagesUploadPostReq was set.
func (o OptImagesUploadPostReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptImagesUploadPostReq) Reset() {
	var v ImagesUploadPostReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptImagesUploadPostReq) SetTo(v ImagesUploadPostReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptImagesUploadPostReq) Get() (v ImagesUploadPostReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptImagesUploadPostReq) Or(d ImagesUploadPostReq) ImagesUploadPostReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMultipartFile returns new OptMultipartFile with value set to v.
func NewOptMultipartFile(v ht.MultipartFile) OptMultipartFile {
	return OptMultipartFile{
		Value: v,
		Set:   true,
	}
}

// OptMultipartFile is optional ht.MultipartFile.
type OptMultipartFile struct {
	Value ht.MultipartFile
	Set   bool
}

// IsSet returns true if OptMultipartFile was set.
func (o OptMultipartFile) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMultipartFile) Reset() {
	var v ht.MultipartFile
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMultipartFile) SetTo(v ht.MultipartFile) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMultipartFile) Get() (v ht.MultipartFile, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMultipartFile) Or(d ht.MultipartFile) ht.MultipartFile {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type VotesGetOK struct{}

// VotesGetOKHeaders wraps VotesGetOK with response headers.
type VotesGetOKHeaders struct {
	AccessControlExposeHeaders OptString
	Connection                 OptString
	ContentLength              OptInt
	Date                       OptString
	KeepAlive                  OptString
	PaginationCount            OptInt
	PaginationLimit            OptInt
	PaginationPage             OptInt
	RateLimitConsumed          OptInt
	RateLimitLimit             OptInt
	RateLimitRemaining         OptInt
	RateLimitReset             OptFloat64
	RetryAfterSeconds          OptInt
	StrictTransportSecurity    OptString
	Vary                       OptString
	XContentTypeOptions        OptString
	XDNSPrefetchControl        OptString
	XDownloadOptions           OptString
	XFrameOptions              OptString
	XResponseTime              OptString
	XXSSProtection             OptString
	Response                   VotesGetOK
}

// GetAccessControlExposeHeaders returns the value of AccessControlExposeHeaders.
func (s *VotesGetOKHeaders) GetAccessControlExposeHeaders() OptString {
	return s.AccessControlExposeHeaders
}

// GetConnection returns the value of Connection.
func (s *VotesGetOKHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *VotesGetOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *VotesGetOKHeaders) GetDate() OptString {
	return s.Date
}

// GetKeepAlive returns the value of KeepAlive.
func (s *VotesGetOKHeaders) GetKeepAlive() OptString {
	return s.KeepAlive
}

// GetPaginationCount returns the value of PaginationCount.
func (s *VotesGetOKHeaders) GetPaginationCount() OptInt {
	return s.PaginationCount
}

// GetPaginationLimit returns the value of PaginationLimit.
func (s *VotesGetOKHeaders) GetPaginationLimit() OptInt {
	return s.PaginationLimit
}

// GetPaginationPage returns the value of PaginationPage.
func (s *VotesGetOKHeaders) GetPaginationPage() OptInt {
	return s.PaginationPage
}

// GetRateLimitConsumed returns the value of RateLimitConsumed.
func (s *VotesGetOKHeaders) GetRateLimitConsumed() OptInt {
	return s.RateLimitConsumed
}

// GetRateLimitLimit returns the value of RateLimitLimit.
func (s *VotesGetOKHeaders) GetRateLimitLimit() OptInt {
	return s.RateLimitLimit
}

// GetRateLimitRemaining returns the value of RateLimitRemaining.
func (s *VotesGetOKHeaders) GetRateLimitRemaining() OptInt {
	return s.RateLimitRemaining
}

// GetRateLimitReset returns the value of RateLimitReset.
func (s *VotesGetOKHeaders) GetRateLimitReset() OptFloat64 {
	return s.RateLimitReset
}

// GetRetryAfterSeconds returns the value of RetryAfterSeconds.
func (s *VotesGetOKHeaders) GetRetryAfterSeconds() OptInt {
	return s.RetryAfterSeconds
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *VotesGetOKHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *VotesGetOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *VotesGetOKHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *VotesGetOKHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *VotesGetOKHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *VotesGetOKHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXResponseTime returns the value of XResponseTime.
func (s *VotesGetOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *VotesGetOKHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *VotesGetOKHeaders) GetResponse() VotesGetOK {
	return s.Response
}

// SetAccessControlExposeHeaders sets the value of AccessControlExposeHeaders.
func (s *VotesGetOKHeaders) SetAccessControlExposeHeaders(val OptString) {
	s.AccessControlExposeHeaders = val
}

// SetConnection sets the value of Connection.
func (s *VotesGetOKHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *VotesGetOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *VotesGetOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetKeepAlive sets the value of KeepAlive.
func (s *VotesGetOKHeaders) SetKeepAlive(val OptString) {
	s.KeepAlive = val
}

// SetPaginationCount sets the value of PaginationCount.
func (s *VotesGetOKHeaders) SetPaginationCount(val OptInt) {
	s.PaginationCount = val
}

// SetPaginationLimit sets the value of PaginationLimit.
func (s *VotesGetOKHeaders) SetPaginationLimit(val OptInt) {
	s.PaginationLimit = val
}

// SetPaginationPage sets the value of PaginationPage.
func (s *VotesGetOKHeaders) SetPaginationPage(val OptInt) {
	s.PaginationPage = val
}

// SetRateLimitConsumed sets the value of RateLimitConsumed.
func (s *VotesGetOKHeaders) SetRateLimitConsumed(val OptInt) {
	s.RateLimitConsumed = val
}

// SetRateLimitLimit sets the value of RateLimitLimit.
func (s *VotesGetOKHeaders) SetRateLimitLimit(val OptInt) {
	s.RateLimitLimit = val
}

// SetRateLimitRemaining sets the value of RateLimitRemaining.
func (s *VotesGetOKHeaders) SetRateLimitRemaining(val OptInt) {
	s.RateLimitRemaining = val
}

// SetRateLimitReset sets the value of RateLimitReset.
func (s *VotesGetOKHeaders) SetRateLimitReset(val OptFloat64) {
	s.RateLimitReset = val
}

// SetRetryAfterSeconds sets the value of RetryAfterSeconds.
func (s *VotesGetOKHeaders) SetRetryAfterSeconds(val OptInt) {
	s.RetryAfterSeconds = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *VotesGetOKHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *VotesGetOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *VotesGetOKHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *VotesGetOKHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *VotesGetOKHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *VotesGetOKHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *VotesGetOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *VotesGetOKHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *VotesGetOKHeaders) SetResponse(val VotesGetOK) {
	s.Response = val
}

type VotesPostCreated struct{}

// VotesPostCreatedHeaders wraps VotesPostCreated with response headers.
type VotesPostCreatedHeaders struct {
	Connection              OptString
	ContentLength           OptInt
	Date                    OptString
	KeepAlive               OptString
	RateLimitConsumed       OptInt
	RateLimitLimit          OptInt
	RateLimitRemaining      OptInt
	RateLimitReset          OptFloat64
	RetryAfterSeconds       OptFloat64
	StrictTransportSecurity OptString
	Vary                    OptString
	XContentTypeOptions     OptString
	XDNSPrefetchControl     OptString
	XDownloadOptions        OptString
	XFrameOptions           OptString
	XResponseTime           OptString
	XXSSProtection          OptString
	Response                VotesPostCreated
}

// GetConnection returns the value of Connection.
func (s *VotesPostCreatedHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *VotesPostCreatedHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *VotesPostCreatedHeaders) GetDate() OptString {
	return s.Date
}

// GetKeepAlive returns the value of KeepAlive.
func (s *VotesPostCreatedHeaders) GetKeepAlive() OptString {
	return s.KeepAlive
}

// GetRateLimitConsumed returns the value of RateLimitConsumed.
func (s *VotesPostCreatedHeaders) GetRateLimitConsumed() OptInt {
	return s.RateLimitConsumed
}

// GetRateLimitLimit returns the value of RateLimitLimit.
func (s *VotesPostCreatedHeaders) GetRateLimitLimit() OptInt {
	return s.RateLimitLimit
}

// GetRateLimitRemaining returns the value of RateLimitRemaining.
func (s *VotesPostCreatedHeaders) GetRateLimitRemaining() OptInt {
	return s.RateLimitRemaining
}

// GetRateLimitReset returns the value of RateLimitReset.
func (s *VotesPostCreatedHeaders) GetRateLimitReset() OptFloat64 {
	return s.RateLimitReset
}

// GetRetryAfterSeconds returns the value of RetryAfterSeconds.
func (s *VotesPostCreatedHeaders) GetRetryAfterSeconds() OptFloat64 {
	return s.RetryAfterSeconds
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *VotesPostCreatedHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *VotesPostCreatedHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *VotesPostCreatedHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *VotesPostCreatedHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *VotesPostCreatedHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *VotesPostCreatedHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXResponseTime returns the value of XResponseTime.
func (s *VotesPostCreatedHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *VotesPostCreatedHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *VotesPostCreatedHeaders) GetResponse() VotesPostCreated {
	return s.Response
}

// SetConnection sets the value of Connection.
func (s *VotesPostCreatedHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *VotesPostCreatedHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *VotesPostCreatedHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetKeepAlive sets the value of KeepAlive.
func (s *VotesPostCreatedHeaders) SetKeepAlive(val OptString) {
	s.KeepAlive = val
}

// SetRateLimitConsumed sets the value of RateLimitConsumed.
func (s *VotesPostCreatedHeaders) SetRateLimitConsumed(val OptInt) {
	s.RateLimitConsumed = val
}

// SetRateLimitLimit sets the value of RateLimitLimit.
func (s *VotesPostCreatedHeaders) SetRateLimitLimit(val OptInt) {
	s.RateLimitLimit = val
}

// SetRateLimitRemaining sets the value of RateLimitRemaining.
func (s *VotesPostCreatedHeaders) SetRateLimitRemaining(val OptInt) {
	s.RateLimitRemaining = val
}

// SetRateLimitReset sets the value of RateLimitReset.
func (s *VotesPostCreatedHeaders) SetRateLimitReset(val OptFloat64) {
	s.RateLimitReset = val
}

// SetRetryAfterSeconds sets the value of RetryAfterSeconds.
func (s *VotesPostCreatedHeaders) SetRetryAfterSeconds(val OptFloat64) {
	s.RetryAfterSeconds = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *VotesPostCreatedHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *VotesPostCreatedHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *VotesPostCreatedHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *VotesPostCreatedHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *VotesPostCreatedHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *VotesPostCreatedHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *VotesPostCreatedHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *VotesPostCreatedHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *VotesPostCreatedHeaders) SetResponse(val VotesPostCreated) {
	s.Response = val
}

type VotesPostReq struct{}

type WebhooksPostOK struct{}

// WebhooksPostOKHeaders wraps WebhooksPostOK with response headers.
type WebhooksPostOKHeaders struct {
	Connection              OptString
	ContentLength           OptInt
	Date                    OptString
	KeepAlive               OptString
	StrictTransportSecurity OptString
	Vary                    OptString
	XContentTypeOptions     OptString
	XDNSPrefetchControl     OptString
	XDownloadOptions        OptString
	XFrameOptions           OptString
	XResponseTime           OptString
	XXSSProtection          OptString
	Response                WebhooksPostOK
}

// GetConnection returns the value of Connection.
func (s *WebhooksPostOKHeaders) GetConnection() OptString {
	return s.Connection
}

// GetContentLength returns the value of ContentLength.
func (s *WebhooksPostOKHeaders) GetContentLength() OptInt {
	return s.ContentLength
}

// GetDate returns the value of Date.
func (s *WebhooksPostOKHeaders) GetDate() OptString {
	return s.Date
}

// GetKeepAlive returns the value of KeepAlive.
func (s *WebhooksPostOKHeaders) GetKeepAlive() OptString {
	return s.KeepAlive
}

// GetStrictTransportSecurity returns the value of StrictTransportSecurity.
func (s *WebhooksPostOKHeaders) GetStrictTransportSecurity() OptString {
	return s.StrictTransportSecurity
}

// GetVary returns the value of Vary.
func (s *WebhooksPostOKHeaders) GetVary() OptString {
	return s.Vary
}

// GetXContentTypeOptions returns the value of XContentTypeOptions.
func (s *WebhooksPostOKHeaders) GetXContentTypeOptions() OptString {
	return s.XContentTypeOptions
}

// GetXDNSPrefetchControl returns the value of XDNSPrefetchControl.
func (s *WebhooksPostOKHeaders) GetXDNSPrefetchControl() OptString {
	return s.XDNSPrefetchControl
}

// GetXDownloadOptions returns the value of XDownloadOptions.
func (s *WebhooksPostOKHeaders) GetXDownloadOptions() OptString {
	return s.XDownloadOptions
}

// GetXFrameOptions returns the value of XFrameOptions.
func (s *WebhooksPostOKHeaders) GetXFrameOptions() OptString {
	return s.XFrameOptions
}

// GetXResponseTime returns the value of XResponseTime.
func (s *WebhooksPostOKHeaders) GetXResponseTime() OptString {
	return s.XResponseTime
}

// GetXXSSProtection returns the value of XXSSProtection.
func (s *WebhooksPostOKHeaders) GetXXSSProtection() OptString {
	return s.XXSSProtection
}

// GetResponse returns the value of Response.
func (s *WebhooksPostOKHeaders) GetResponse() WebhooksPostOK {
	return s.Response
}

// SetConnection sets the value of Connection.
func (s *WebhooksPostOKHeaders) SetConnection(val OptString) {
	s.Connection = val
}

// SetContentLength sets the value of ContentLength.
func (s *WebhooksPostOKHeaders) SetContentLength(val OptInt) {
	s.ContentLength = val
}

// SetDate sets the value of Date.
func (s *WebhooksPostOKHeaders) SetDate(val OptString) {
	s.Date = val
}

// SetKeepAlive sets the value of KeepAlive.
func (s *WebhooksPostOKHeaders) SetKeepAlive(val OptString) {
	s.KeepAlive = val
}

// SetStrictTransportSecurity sets the value of StrictTransportSecurity.
func (s *WebhooksPostOKHeaders) SetStrictTransportSecurity(val OptString) {
	s.StrictTransportSecurity = val
}

// SetVary sets the value of Vary.
func (s *WebhooksPostOKHeaders) SetVary(val OptString) {
	s.Vary = val
}

// SetXContentTypeOptions sets the value of XContentTypeOptions.
func (s *WebhooksPostOKHeaders) SetXContentTypeOptions(val OptString) {
	s.XContentTypeOptions = val
}

// SetXDNSPrefetchControl sets the value of XDNSPrefetchControl.
func (s *WebhooksPostOKHeaders) SetXDNSPrefetchControl(val OptString) {
	s.XDNSPrefetchControl = val
}

// SetXDownloadOptions sets the value of XDownloadOptions.
func (s *WebhooksPostOKHeaders) SetXDownloadOptions(val OptString) {
	s.XDownloadOptions = val
}

// SetXFrameOptions sets the value of XFrameOptions.
func (s *WebhooksPostOKHeaders) SetXFrameOptions(val OptString) {
	s.XFrameOptions = val
}

// SetXResponseTime sets the value of XResponseTime.
func (s *WebhooksPostOKHeaders) SetXResponseTime(val OptString) {
	s.XResponseTime = val
}

// SetXXSSProtection sets the value of XXSSProtection.
func (s *WebhooksPostOKHeaders) SetXXSSProtection(val OptString) {
	s.XXSSProtection = val
}

// SetResponse sets the value of Response.
func (s *WebhooksPostOKHeaders) SetResponse(val WebhooksPostOK) {
	s.Response = val
}

type WebhooksPostReq struct{}
