// Code generated by ogen, DO NOT EDIT.

package dadata

// BreedsBreedIDFactsGetParams is parameters of GET /breeds/{breed_id}/facts operation.
type BreedsBreedIDFactsGetParams struct {
	Limit   OptInt
	Page    OptInt
	Order   OptString
	BreedID string
}

// BreedsBreedIDGetParams is parameters of GET /breeds/{breed_id} operation.
type BreedsBreedIDGetParams struct {
	BreedID string
}

// BreedsGetParams is parameters of GET /breeds operation.
type BreedsGetParams struct {
	Limit OptInt
	Page  OptInt
}

// BreedsSearchGetParams is parameters of GET /breeds/search operation.
type BreedsSearchGetParams struct {
	// Search term for breed name.
	Q OptString
	// [optional] whether to attach the reference_image_id image or not.
	AttachImage OptInt
}

// FavouritesGetParams is parameters of GET /favourites operation.
type FavouritesGetParams struct {
	XAPIKey string
}

// FavouritesPostParams is parameters of POST /favourites operation.
type FavouritesPostParams struct {
	XAPIKey string
}

// ImagesBkIEhN3pGGetParams is parameters of GET /images/BkIEhN3pG operation.
type ImagesBkIEhN3pGGetParams struct {
	// [optional]  will save this request to your account analytics.
	XAPIKey OptString
}

// ImagesGetParams is parameters of GET /images/ operation.
type ImagesGetParams struct {
	// - will return all the images from your account.
	XAPIKey string
	// [Optional] number of images to return valid  1 to 10 - default: 1.
	Limit OptInt
	// [Optional] only works if account_id is present to page through your own uploads.
	Page OptInt
	// [Optional] only works if account_id is present, either ASC or DESC - ascending or descending.
	Order OptString
}

// ImagesSearchGetParams is parameters of GET /images/search operation.
type ImagesSearchGetParams struct {
	// [optional] without it only the a basic set of images can be searched.
	XAPIKey OptString
	// [optional] thumb , small, med or full - small is perfect for Discord.
	Size OptString
	// [optional] a comma separated strig of types to return e.g. jpg,png for static, or gif for gifs.
	MimeTypes OptString
	// [optional] json | src.
	Format OptString
	// [optional] - only return images with breed data.
	HasBreeds OptBool
	// [optional] default:RANDOM - RANDOM | ASC | DESC.
	Order OptString
	// [optional] paginate through results.
	Page OptInt
	// [optional] number of results to return, up to 25 with a valid API-Key.
	Limit OptInt
}

// ImagesUploadPostParams is parameters of POST /images/upload operation.
type ImagesUploadPostParams struct {
	// - saves the uploaded image to your account.
	XAPIKey string
}

// VotesGetParams is parameters of GET /votes operation.
type VotesGetParams struct {
	XAPIKey string
}

// VotesPostParams is parameters of POST /votes operation.
type VotesPostParams struct {
	XAPIKey string
}
