// Code generated by ogen, DO NOT EDIT.

package dadata

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ApikeyAuth provides apikeyAuth security value.
	ApikeyAuth(ctx context.Context, operationName string) (ApikeyAuth, error)
}

func (s *Client) securityApikeyAuth(ctx context.Context, operationName string, req *http.Request) error {
	t, err := s.sec.ApikeyAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ApikeyAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
